name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  release:
    types: [ published ]

jobs:

  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [ windows, freebsd, openbsd, linux, dragonfly, darwin ]
        goarch: [ amd64, 386 ]
        exclude:
          # Exclude i386 on darwin and dragonfly.
          - goarch: 386
            goos: dragonfly
          - goarch: 386
            goos: darwin
          - goarch: 386
            goos: openbsd
        include:
          # BEIGIN MacOS ARM64
          - goos: darwin
            goarch: arm64
          # END MacOS ARM64
          # BEGIN Linux ARM 5 6 7
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 5
          # END Linux ARM 5 6 7
          # BEGIN Android ARM 8
          - goos: android
            goarch: arm64
          # END Android ARM 8
          # BEGIN Other architectures
          # BEGIN riscv64 & ARM64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: riscv64
          # END riscv64 & ARM64
          # BEGIN MIPS
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips
          # END MIPS
          # BEGIN PPC
          # - goos: linux # Removed due to the unsupport of shirou/gopsutil 
          #   goarch: ppc64
          - goos: linux
            goarch: ppc64le
          # END PPC
          # BEGIN FreeBSD ARM
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: arm
            goarm: 7
          # END FreeBSD ARM
          # BEGIN S390X
          - goos: linux
            goarch: s390x
          # END S390X
          # END Other architectures
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Show workflow information
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Get project dependencies
        run: go mod download


      - name: Build AikoR
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/AikoR -trimpath -ldflags "-s -w -buildid=" ./AikoR

      - name: Build Mips softfloat AikoR
        if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
        run: |
          GOMIPS=softfloat go build -v -o build_assets/AikoR_softfloat -trimpath -ldflags "-s -w -buildid=" ./AikoR
      - name: Rename Windows AikoR
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv AikoR AikoR.exe

      - name: Prepare to release
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          retry_wait_seconds: 60
          max_attempts: 5
          command: |
            cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
            cp ${GITHUB_WORKSPACE}/LICENSE ./build_assets/LICENSE
            cp ${GITHUB_WORKSPACE}/AikoR/dns.json ./build_assets/dns.json
            cp ${GITHUB_WORKSPACE}/AikoR/route.json ./build_assets/route.json
            cp ${GITHUB_WORKSPACE}/AikoR/custom_outbound.json ./build_assets/custom_outbound.json
            cp ${GITHUB_WORKSPACE}/AikoR/custom_inbound.json ./build_assets/custom_inbound.json
            cp ${GITHUB_WORKSPACE}/AikoR/AikoBlock ./build_assets/AikoBlock
            cp ${GITHUB_WORKSPACE}/AikoR/acces.log.example ./build_assets/acces.log
            cp ${GITHUB_WORKSPACE}/AikoR/error.log.example ./build_assets/error.log
            cp ${GITHUB_WORKSPACE}/AikoR/aiko.yml.example ./build_assets/aiko.yml
            LIST=('geoip geoip geoip' 'domain-list-community dlc geosite')
            for i in "${LIST[@]}"
            do
              INFO=($(echo $i | awk 'BEGIN{FS=" ";OFS=" "} {print $1,$2,$3}'))
              DOWNLOAD_URL="https://raw.githubusercontent.com/v2fly/${INFO[0]}/release/${INFO[1]}.dat"
              FILE_NAME="${INFO[2]}.dat"
              echo -e "Downloading ${DOWNLOAD_URL}..."
              curl -L "${DOWNLOAD_URL}" -o ./build_assets/${FILE_NAME}
              echo -e "Verifying HASH key..."
              HASH="$(curl -sL "${DOWNLOAD_URL}.sha256sum" | awk -F ' ' '{print $1}')"
              [ "$(sha256sum "./build_assets/${FILE_NAME}" | awk -F ' ' '{print $1}')" == "${HASH}" ] || { echo -e "The HASH key of ${FILE_NAME} does not match cloud one."; exit 1; }
            done
      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../AikoR-$ASSET_NAME.zip .
          popd || exit 1
          FILE=./AikoR-$ASSET_NAME.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done
      - name: Change the name
        run: |
          mv build_assets AikoR-$ASSET_NAME
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AikoR-${{ steps.get_filename.outputs.ASSET_NAME }}
          path: |
            ./AikoR-${{ steps.get_filename.outputs.ASSET_NAME }}/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./AikoR-${{ steps.get_filename.outputs.ASSET_NAME }}.zip*
          tag: ${{ github.ref }}
          file_glob: true